CREATE TABLE DIM_PRODUCT_MANUFACTURERS (
MANUFACTURER_ID INT NOT NULL,
NAME VARCHAR(50) NOT NULL,
ADDRESS_LINE_1 VARCHAR(100) NOT NULL,
ADDRESS_LINE_2 VARCHAR(100),
CITY VARCHAR(50) NOT NULL,
STATE VARCHAR(50) NOT NULL,
ZIP_CODE VARCHAR(10) NOT NULL,
COUNTRY VARCHAR(50) NOT NULL,
PRIMARY KEY (MANUFACTURER_ID)
);